// server/serve.ts
import { createServer } from "node:http";
import { readFileSync as readFileSync2, existsSync as existsSync2 } from "node:fs";
import path2 from "node:path";
import * as sea from "node:sea";

// server/innertube.ts
import { createHash } from "node:crypto";

// server/chrome.ts
import { spawn } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
var dataDir = () => process.env.YTM_DATA || path.join(process.cwd(), "data");
var profileDir = () => path.join(dataDir(), "chrome-profile");
var sessionFile = () => path.join(dataDir(), "session.json");
var cookiesTxt = () => path.join(dataDir(), "cookies.txt");
var DEBUG_PORT = 9222;
var CAPTURE_TIMEOUT_MS = 5 * 60 * 1e3;
var POLL_INTERVAL_MS = 2e3;
var AUTH_COOKIE = "SAPISID";
var CHROME_CANDIDATES = [
  process.env.CHROME_PATH || "",
  // Windows
  "C:/Program Files/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
  path.join(
    process.env.LOCALAPPDATA || "",
    "Google/Chrome/Application/chrome.exe"
  ),
  // macOS
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/Applications/Chromium.app/Contents/MacOS/Chromium",
  // Linux
  "/usr/bin/google-chrome",
  "/usr/bin/google-chrome-stable",
  "/usr/bin/chromium",
  "/usr/bin/chromium-browser",
  "/snap/bin/chromium"
];
var cached;
function getSession() {
  if (cached === void 0) {
    cached = null;
    if (existsSync(sessionFile())) {
      try {
        const raw = readFileSync(sessionFile(), "utf8").trim();
        if (raw) cached = JSON.parse(raw);
      } catch {
        cached = null;
      }
    }
  }
  return cached;
}
function isAuthenticated() {
  return getSession() !== null;
}
function logout() {
  cached = null;
  for (const f of [sessionFile(), cookiesTxt()]) {
    try {
      if (existsSync(f)) writeFileSync(f, "");
    } catch {
    }
  }
}
async function cdpTargets() {
  const res = await fetch(`http://127.0.0.1:${DEBUG_PORT}/json`);
  return await res.json();
}
async function cdpBrowserWs() {
  const res = await fetch(`http://127.0.0.1:${DEBUG_PORT}/json/version`);
  const v = await res.json();
  return v.webSocketDebuggerUrl;
}
function cdpCall(wsUrl, method, params = {}) {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket(wsUrl);
    const id = 1;
    const timer = setTimeout(() => {
      try {
        ws.close();
      } catch {
      }
      reject(new Error(`CDP ${method} timed out`));
    }, 1e4);
    ws.addEventListener("open", () => {
      ws.send(JSON.stringify({ id, method, params }));
    });
    ws.addEventListener("message", (ev) => {
      const msg = JSON.parse(String(ev.data));
      if (msg.id !== id) return;
      clearTimeout(timer);
      ws.close();
      if (msg.error) reject(new Error(`CDP ${method}: ${msg.error.message}`));
      else resolve(msg.result);
    });
    ws.addEventListener("error", () => {
      clearTimeout(timer);
      reject(new Error(`CDP socket error for ${method}`));
    });
  });
}
async function getAllCookies() {
  const browserWs = await cdpBrowserWs();
  const { cookies } = await cdpCall(
    browserWs,
    "Storage.getCookies"
  );
  return cookies ?? [];
}
async function getYtcfg() {
  const empty = {
    loggedIn: false,
    visitorData: null,
    apiKey: null,
    clientVersion: null,
    context: null
  };
  const targets = await cdpTargets();
  const page = targets.find(
    (t) => t.type === "page" && t.url.includes("music.youtube.com")
  );
  if (!page) return empty;
  try {
    const { result } = await cdpCall(
      page.webSocketDebuggerUrl,
      "Runtime.evaluate",
      {
        expression: `JSON.stringify((function () {
          var g = (window.ytcfg && ytcfg.get) ? ytcfg.get.bind(ytcfg) : function () { return undefined; };
          var ctx = g('INNERTUBE_CONTEXT') || null;
          return {
            loggedIn: g('LOGGED_IN') === true,
            visitorData: g('VISITOR_DATA') || (ctx && ctx.client && ctx.client.visitorData) || null,
            apiKey: g('INNERTUBE_API_KEY') || null,
            clientVersion: g('INNERTUBE_CLIENT_VERSION') || (ctx && ctx.client && ctx.client.clientVersion) || null,
            context: ctx,
          };
        })())`,
        returnByValue: true
      }
    );
    return result?.value ? JSON.parse(result.value) : empty;
  } catch {
    return empty;
  }
}
function toCookieHeader(cookies) {
  const byName = /* @__PURE__ */ new Map();
  for (const c of cookies) {
    if (c.domain.includes("google") || c.domain.includes("youtube")) {
      byName.set(c.name, c.value);
    }
  }
  return [...byName].map(([k, v]) => `${k}=${v}`).join("; ");
}
function toNetscape(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# generated by ytmusicnative"];
  for (const c of cookies) {
    if (!c.domain.includes("youtube") && !c.domain.includes("google")) continue;
    const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`;
    const includeSub = "TRUE";
    const expires = c.expires > 0 ? Math.floor(c.expires) : 0;
    lines.push(
      [
        domain,
        includeSub,
        c.path || "/",
        c.secure ? "TRUE" : "FALSE",
        String(expires),
        c.name,
        c.value
      ].join("	")
    );
  }
  return lines.join("\n") + "\n";
}
function chromePath() {
  const found = CHROME_CANDIDATES.find((p) => p && existsSync(p));
  if (!found)
    throw new Error(
      "Could not find Chrome/Chromium. Install it or set CHROME_PATH."
    );
  return found;
}
var loginState = { status: "idle" };
function getLoginState() {
  return loginState;
}
function startLogin() {
  if (loginState.status === "waiting") return loginState;
  mkdirSync(profileDir(), { recursive: true });
  loginState = { status: "waiting" };
  const proc = spawn(
    chromePath(),
    [
      `--remote-debugging-port=${DEBUG_PORT}`,
      `--user-data-dir=${profileDir()}`,
      "--no-first-run",
      "--no-default-browser-check",
      "--new-window",
      "https://music.youtube.com/"
    ],
    { detached: true, stdio: "ignore" }
  );
  proc.unref();
  void watchForLogin();
  return loginState;
}
async function watchForLogin() {
  const deadline = Date.now() + CAPTURE_TIMEOUT_MS;
  await delay(1500);
  while (Date.now() < deadline) {
    try {
      const cookies = await getAllCookies();
      const signedIn = cookies.some((c) => c.name === AUTH_COOKIE && c.value);
      if (signedIn) {
        const cfg = await getYtcfg();
        if (cfg.loggedIn && cfg.visitorData) {
          await capture(cookies, cfg);
          loginState = { status: "captured" };
          return;
        }
      }
    } catch {
    }
    await delay(POLL_INTERVAL_MS);
  }
  loginState = {
    status: "error",
    message: "Timed out waiting for login. Close Chrome and try again."
  };
}
async function capture(cookies, cfg) {
  mkdirSync(dataDir(), { recursive: true });
  const session = {
    cookie: toCookieHeader(cookies),
    visitor_data: cfg.visitorData,
    apiKey: cfg.apiKey,
    clientVersion: cfg.clientVersion,
    context: cfg.context,
    capturedAt: Date.now()
  };
  writeFileSync(sessionFile(), JSON.stringify(session, null, 2));
  writeFileSync(cookiesTxt(), toNetscape(cookies));
  cached = session;
}
function delay(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

// server/innertube.ts
var MUSIC_ORIGIN = "https://music.youtube.com";
var MUSIC_API = `${MUSIC_ORIGIN}/youtubei/v1`;
var YT_API = "https://www.youtube.com/youtubei/v1";
var WEB_REMIX_NAME = 67;
var WEB_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36";
var ANDROID_VR_NAME = 28;
var ANDROID_VR = {
  clientName: "ANDROID_VR",
  deviceMake: "Oculus",
  deviceModel: "Quest 3",
  androidSdkVersion: 32,
  osName: "Android",
  osVersion: "12",
  hl: "en",
  gl: "US"
};
var ANDROID_VR_VERSIONS = ["1.68.10", "1.66.10", "1.65.10", "1.64.10"];
var vrVersion = null;
function vrUserAgent(version) {
  return `com.google.android.apps.youtube.vr.oculus/${version} (Linux; U; Android 12; eureka-user Build/SQ3A.220605.009.A1) gzip`;
}
function cookieValue(cookie, name) {
  const m = cookie.match(new RegExp(`(?:^|;\\s*)${name}=([^;]+)`));
  return m ? m[1] : null;
}
function sapisidAuth(cookie) {
  const sapisid = cookieValue(cookie, "SAPISID") || cookieValue(cookie, "__Secure-3PAPISID") || cookieValue(cookie, "__Secure-1PAPISID");
  if (!sapisid) return null;
  const ts = Math.floor(Date.now() / 1e3);
  const hash = createHash("sha1").update(`${ts} ${sapisid} ${MUSIC_ORIGIN}`).digest("hex");
  return `SAPISIDHASH ${ts}_${hash}`;
}
function webContext() {
  const s = getSession();
  const captured = s?.context ?? null;
  const client = {
    ...captured?.client ?? {},
    clientName: "WEB_REMIX",
    clientVersion: s?.clientVersion ?? captured?.client?.clientVersion ?? "1.20240911.01.00",
    hl: captured?.client?.hl ?? "de",
    gl: captured?.client?.gl ?? "DE",
    visitorData: s?.visitor_data ?? captured?.client?.visitorData ?? void 0
  };
  return { ...captured ?? {}, client, user: captured?.user ?? {} };
}
var NotAuthedError = class extends Error {
  constructor() {
    super("not authenticated");
  }
};
async function callMusic(endpoint2, body) {
  const s = getSession();
  if (!s) throw new NotAuthedError();
  const auth = sapisidAuth(s.cookie);
  if (!auth) throw new NotAuthedError();
  const url = `${MUSIC_API}/${endpoint2}?prettyPrint=false${s.apiKey ? `&key=${s.apiKey}` : ""}`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "*/*",
      Cookie: s.cookie,
      Authorization: auth,
      Origin: MUSIC_ORIGIN,
      "X-Origin": MUSIC_ORIGIN,
      Referer: `${MUSIC_ORIGIN}/`,
      "X-Goog-AuthUser": "0",
      ...s.visitor_data ? { "X-Goog-Visitor-Id": s.visitor_data } : {},
      "X-Youtube-Client-Name": String(WEB_REMIX_NAME),
      "X-Youtube-Client-Version": s.clientVersion ?? "1.20240911.01.00",
      "User-Agent": WEB_UA
    },
    body: JSON.stringify({ context: webContext(), ...body })
  });
  if (!res.ok) {
    throw new Error(`InnerTube ${endpoint2} ${res.status}: ${await res.text()}`);
  }
  return await res.json();
}
async function songDetails(videoId) {
  const pr = await callMusic("player", {
    videoId,
    playbackContext: { contentPlaybackContext: { html5Preference: "HTML5_PREF_WANTS" } },
    contentCheckOk: true,
    racyCheckOk: true
  });
  const vd = pr?.videoDetails ?? {};
  const mf = pr?.microformat?.microformatDataRenderer ?? pr?.microformat?.playerMicroformatRenderer ?? {};
  const thumbs = vd?.thumbnail?.thumbnails ?? [];
  return {
    videoId: vd.videoId ?? videoId,
    title: vd.title ?? null,
    author: vd.author ?? null,
    channelId: vd.channelId ?? null,
    lengthSeconds: vd.lengthSeconds ? Number(vd.lengthSeconds) : null,
    viewCount: vd.viewCount ? Number(vd.viewCount) : null,
    musicVideoType: vd.musicVideoType ?? null,
    thumbnail: thumbs.length ? thumbs[thumbs.length - 1].url : null,
    publishDate: mf.publishDate ?? mf.uploadDate ?? null,
    category: mf.category ?? null
  };
}
var CPN_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
function makeCpn() {
  let s = "";
  for (let i = 0; i < 16; i++) s += CPN_CHARS[Math.floor(Math.random() * 64)];
  return s;
}
async function addHistoryItem(videoId) {
  const s = getSession();
  if (!s) throw new NotAuthedError();
  const pr = await callMusic("player", {
    videoId,
    playbackContext: { contentPlaybackContext: { html5Preference: "HTML5_PREF_WANTS" } },
    contentCheckOk: true,
    racyCheckOk: true
  });
  const base = pr?.playbackTracking?.videostatsPlaybackUrl?.baseUrl;
  if (!base) throw new Error("no playback tracking url");
  const url = new URL(base);
  url.searchParams.set("ver", "2");
  url.searchParams.set("c", "WEB_REMIX");
  url.searchParams.set("cpn", makeCpn());
  const res = await fetch(url.toString(), {
    headers: {
      Cookie: s.cookie,
      Origin: MUSIC_ORIGIN,
      Referer: `${MUSIC_ORIGIN}/`,
      "X-Goog-AuthUser": "0",
      ...s.visitor_data ? { "X-Goog-Visitor-Id": s.visitor_data } : {},
      "User-Agent": WEB_UA
    }
  });
  if (!res.ok) throw new Error(`history ping ${res.status}`);
}
async function resolveAlbumBrowseId(audioPlaylistId) {
  const s = getSession();
  const res = await fetch(`${MUSIC_ORIGIN}/playlist?list=${encodeURIComponent(audioPlaylistId)}`, {
    headers: {
      ...s?.cookie ? { Cookie: s.cookie } : {},
      ...s?.visitor_data ? { "X-Goog-Visitor-Id": s.visitor_data } : {},
      "Accept-Language": "de",
      "User-Agent": WEB_UA
    }
  });
  if (!res.ok) return null;
  const html = await res.text();
  return html.match(/MPREb_[A-Za-z0-9_-]+/)?.[0] ?? null;
}
async function uploadSong(filePath) {
  const s = getSession();
  if (!s) throw new NotAuthedError();
  const { readFile } = await import("node:fs/promises");
  const { basename } = await import("node:path");
  const data = await readFile(filePath);
  const headers = {
    Cookie: s.cookie,
    Authorization: sapisidAuth(s.cookie) ?? "",
    Origin: MUSIC_ORIGIN,
    "X-Origin": MUSIC_ORIGIN,
    Referer: `${MUSIC_ORIGIN}/`,
    "X-Goog-AuthUser": "0",
    "User-Agent": WEB_UA
  };
  const start = await fetch("https://upload.youtube.com/upload/usermusic/http?authuser=0", {
    method: "POST",
    headers: {
      ...headers,
      "X-Goog-Upload-Command": "start",
      "X-Goog-Upload-Header-Content-Length": String(data.byteLength),
      "X-Goog-Upload-Protocol": "resumable"
    },
    body: basename(filePath)
  });
  const uploadUrl = start.headers.get("X-Goog-Upload-URL");
  if (!uploadUrl) throw new Error(`upload start failed ${start.status}`);
  const done = await fetch(uploadUrl, {
    method: "POST",
    headers: {
      ...headers,
      "X-Goog-Upload-Command": "upload, finalize",
      "X-Goog-Upload-Offset": "0"
    },
    body: data
  });
  return done.status === 200;
}
async function callPlayerAs(videoId, version) {
  const visitorData = getSession()?.visitor_data;
  const userAgent = vrUserAgent(version);
  const client = {
    ...ANDROID_VR,
    clientVersion: version,
    userAgent,
    ...visitorData ? { visitorData } : {}
  };
  const res = await fetch(`${YT_API}/player?prettyPrint=false`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "*/*",
      Origin: "https://www.youtube.com",
      ...visitorData ? { "X-Goog-Visitor-Id": visitorData } : {},
      "X-Youtube-Client-Name": String(ANDROID_VR_NAME),
      "X-Youtube-Client-Version": version,
      "User-Agent": userAgent
    },
    body: JSON.stringify({
      context: { client },
      videoId,
      playbackContext: { contentPlaybackContext: { html5Preference: "HTML5_PREF_WANTS" } },
      contentCheckOk: true,
      racyCheckOk: true
    })
  });
  if (!res.ok) {
    throw new Error(`player ${res.status}: ${await res.text()}`);
  }
  return res.json();
}
function hasReadyAudio(pr) {
  return (pr?.streamingData?.adaptiveFormats ?? []).some(
    (f) => f.url && typeof f.mimeType === "string" && f.mimeType.includes("audio")
  );
}
async function callPlayer(videoId) {
  const order = vrVersion ? [vrVersion, ...ANDROID_VR_VERSIONS.filter((v) => v !== vrVersion)] : ANDROID_VR_VERSIONS;
  let last = null;
  for (const version of order) {
    const pr = await callPlayerAs(videoId, version);
    if (hasReadyAudio(pr)) {
      vrVersion = version;
      return pr;
    }
    last = pr;
    const status = pr?.playabilityStatus?.status;
    if (status && status !== "OK" && status !== "LOGIN_REQUIRED") break;
  }
  return last;
}
async function streamInfo(videoId) {
  const pr = await callPlayer(videoId);
  const formats = pr?.streamingData?.adaptiveFormats ?? [];
  const f = formats.filter((x) => x.url && typeof x.mimeType === "string" && x.mimeType.includes("audio")).sort((a, b) => (b.bitrate ?? 0) - (a.bitrate ?? 0))[0] ?? {};
  const mime = f.mimeType ?? "";
  const container = mime.split(";")[0]?.split("/")[1] ?? null;
  const codec = /codecs="([^"]+)"/.exec(mime)?.[1] ?? null;
  return {
    videoId,
    itag: f.itag ?? null,
    codec,
    container,
    bitrate: f.bitrate ?? null,
    averageBitrate: f.averageBitrate ?? null,
    audioSampleRate: f.audioSampleRate ?? null,
    audioChannels: f.audioChannels ?? null,
    contentLength: f.contentLength ?? null,
    loudnessDb: pr?.playerConfig?.audioConfig?.loudnessDb ?? null,
    client: "ANDROID_VR"
  };
}
async function resolveAudio(videoId) {
  const pr = await callPlayer(videoId);
  const status = pr?.playabilityStatus?.status;
  const formats = pr?.streamingData?.adaptiveFormats ?? [];
  const audio = formats.filter((f2) => f2.url && typeof f2.mimeType === "string" && f2.mimeType.includes("audio")).sort((a, b) => (b.bitrate ?? 0) - (a.bitrate ?? 0));
  if (!audio.length) {
    const reason = pr?.playabilityStatus?.reason || status || "no audio formats";
    throw new Error(`player: ${reason}`);
  }
  const f = audio[0];
  return {
    itag: f.itag,
    url: f.url,
    mimeType: f.mimeType,
    bitrate: f.bitrate ?? 0,
    contentLength: f.contentLength
  };
}

// server/premium.ts
import { createHash as createHash2 } from "node:crypto";
import { createContext, runInContext } from "node:vm";
var MUSIC_ORIGIN2 = "https://music.youtube.com";
var WEB_UA2 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36";
var PREMIUM_ITAGS = [141, 774];
var assetsCache = null;
var ASSETS_TTL_MS = 30 * 60 * 1e3;
var playerCache = /* @__PURE__ */ new Map();
var PLAYER_TTL_MS = 2 * 60 * 1e3;
function sapisidAuth2(cookie) {
  const sap = cookie.match(
    /(?:^|;\s*)(?:SAPISID|__Secure-3PAPISID|__Secure-1PAPISID)=([^;]+)/
  )?.[1];
  if (!sap) throw new Error("no SAPISID cookie");
  const ts = Math.floor(Date.now() / 1e3);
  const hash = createHash2("sha1").update(`${ts} ${sap} ${MUSIC_ORIGIN2}`).digest("hex");
  return `SAPISIDHASH ${ts}_${hash}`;
}
function matchBrace(s, open) {
  let d = 0;
  for (let i = open; i < s.length; i++) {
    if (s[i] === "{") d++;
    else if (s[i] === "}" && !--d) return i + 1;
  }
  return -1;
}
function makePortal(baseJs) {
  const swap = baseJs.match(
    /[A-Za-z0-9$_]+:function\(([A-Za-z0-9$_]+),([A-Za-z0-9$_]+)\)\{var [A-Za-z0-9$_]+=\1\[0\];\1\[0\]=\1\[\2%\1(?:\.length|\[([A-Za-z0-9$_]+)\[\d+\]\])\]/
  );
  if (!swap) throw new Error("swap helper not found (player structure changed)");
  const ARR = swap[3] || null;
  const objHead = [
    ...baseJs.slice(0, baseJs.indexOf(swap[0])).matchAll(/([A-Za-z0-9$_]+)=\{/g)
  ].pop();
  if (!objHead) throw new Error("helper object not found");
  const objEnd = matchBrace(baseJs, baseJs.indexOf("{", objHead.index));
  const src = baseJs.slice(0, objEnd) + ";globalThis.__ev=function(_x){try{return eval(_x)}catch(e){return undefined}};" + baseJs.slice(objEnd);
  const makeStub = () => {
    const f = () => stub;
    const stub = new Proxy(f, {
      get: (_, p) => p === "length" ? 0 : p === "toString" || p === Symbol.toPrimitive ? () => "" : stub,
      set: () => true,
      apply: () => stub,
      construct: () => stub,
      has: () => true
    });
    return stub;
  };
  const ctx = {
    navigator: {
      userAgent: WEB_UA2,
      platform: "Win32",
      languages: ["en"],
      language: "en"
    },
    location: {
      href: MUSIC_ORIGIN2 + "/",
      protocol: "https:",
      hostname: "music.youtube.com",
      origin: MUSIC_ORIGIN2,
      search: "",
      hash: "",
      pathname: "/"
    },
    document: makeStub(),
    XMLHttpRequest: function() {
      return makeStub();
    },
    setTimeout: () => 0,
    clearTimeout: () => {
    },
    setInterval: () => 0,
    clearInterval: () => {
    },
    console: { log() {
    }, warn() {
    }, error() {
    }, info() {
    }, debug() {
    } },
    Math,
    Date,
    JSON,
    parseInt,
    parseFloat,
    isNaN,
    isFinite,
    encodeURIComponent,
    decodeURIComponent,
    encodeURI,
    decodeURI,
    escape,
    unescape,
    TextEncoder,
    TextDecoder,
    URL,
    URLSearchParams,
    Array,
    Object,
    String,
    Number,
    Boolean,
    RegExp,
    Error,
    Symbol,
    Map,
    Set,
    WeakMap,
    WeakSet,
    Promise,
    Function,
    Reflect,
    Proxy,
    Uint8Array,
    Uint32Array,
    Int32Array,
    ArrayBuffer,
    DataView,
    Float64Array,
    btoa: (x) => Buffer.from(x, "binary").toString("base64"),
    atob: (x) => Buffer.from(x, "base64").toString("binary"),
    performance: { now: () => Date.now() }
  };
  ctx.window = ctx;
  ctx.self = ctx;
  ctx.globalThis = ctx;
  ctx.top = ctx;
  createContext(ctx);
  runInContext(src, ctx, { timeout: 1e4 });
  if (typeof ctx.__ev !== "function") throw new Error("eval-portal did not initialise");
  const evT = (expr, ms = 150) => {
    try {
      runInContext(`globalThis.__r=__ev(${JSON.stringify(expr)})`, ctx, { timeout: ms });
      return ctx.__r;
    } catch {
      return void 0;
    }
  };
  return { ev: ctx.__ev, evT, ARR };
}
var valid = (x, ref) => typeof x === "string" && x.length >= 8 && x !== ref && /^[A-Za-z0-9_-]+$/.test(x);
var validN = (x, ref) => valid(x, ref) && !x.includes(ref) && x.length <= ref.length + 12;
function isReorderOf(x, ref) {
  if (typeof x !== "string" || x.length < 8 || x === ref || x.length > ref.length)
    return false;
  const cnt = {};
  for (const c of ref) cnt[c] = (cnt[c] || 0) + 1;
  for (const c of x) {
    if (!cnt[c]) return false;
    cnt[c]--;
  }
  return x.length >= ref.length - 30;
}
function descramble(baseJs, portal, sIn, nIn) {
  const { ev, ARR } = portal;
  let sig = null;
  let sigFn = null;
  const sc = baseJs.match(
    /([A-Za-z0-9$_]+)\((\d+),(\d+),([A-Za-z0-9$_]+)\((\d+),(\d+),[A-Za-z0-9$_.]+\.s\)\)/
  );
  if (sc) {
    const [, S, A, B, E, C, D] = sc;
    const r = ev(`${S}(${A},${B},${E}(${C},${D},${JSON.stringify(sIn)}))`);
    if (typeof r === "string" && r.length >= 10) sig = r;
  }
  if (!sig) {
    const cand = /* @__PURE__ */ new Set();
    for (const m of baseJs.matchAll(/([A-Za-z0-9$_]+)\(decodeURIComponent\(/g))
      cand.add(m[1]);
    for (const m of baseJs.matchAll(
      /([A-Za-z0-9$_]+)=function\(\w\)\{\w=\w(?:\.split\(""\)|\[[A-Za-z0-9$_]+\[\d+\]\]\([A-Za-z0-9$_]+\[\d+\]\))/g
    ))
      cand.add(m[1]);
    for (const fn of cand) {
      const r = ev(`${fn}(${JSON.stringify(sIn)})`);
      if (isReorderOf(r, sIn)) {
        sig = r;
        sigFn = fn;
        break;
      }
    }
  }
  if (!sig) throw new Error("signature: no strategy matched (player structure changed)");
  let nOut = null;
  if (nIn) {
    const nMatch = ARR ? baseJs.match(
      new RegExp(
        "z\\[" + ARR + "\\[([A-Za-z0-9$_]+)\\^(\\d+)\\]\\]\\(" + ARR + "\\[\\1\\^\\d+\\]\\)\\s*[,;]\\s*(?:var\\s+)?[A-Za-z0-9$_]+=\\["
      )
    ) : null;
    if (nMatch) {
      const splitOff = Number(nMatch[2]);
      const fn = [
        ...baseJs.slice(0, nMatch.index).matchAll(/([A-Za-z0-9$_]+)=function\(/g)
      ].pop();
      const nDriver = fn ? fn[1] : null;
      const splitIdx = ev(`${ARR}.indexOf("split")`);
      if (nDriver && typeof splitIdx === "number" && splitIdx >= 0) {
        const Q = splitIdx ^ splitOff;
        const counts = {};
        for (let M = 0; M < 64; M++) {
          const r = ev(`${nDriver}(${M},${Q ^ M},${JSON.stringify(nIn)})`);
          if (validN(r, nIn)) counts[r] = (counts[r] || 0) + 1;
        }
        const ranked = Object.entries(counts).sort((a, b) => b[1] - a[1]);
        if (ranked.length) nOut = ranked[0][0];
      }
    }
    if (!nOut && ARR) {
      const splitIdx = ev(`${ARR}.indexOf("split")`);
      const splitRe = new RegExp(
        "[A-Za-z0-9$_]+\\[" + ARR + "\\[([A-Za-z0-9$_]+)\\^(\\d+)\\]\\]\\(" + ARR + "\\[([A-Za-z0-9$_]+)\\^(\\d+)\\]\\)",
        "g"
      );
      const tried = /* @__PURE__ */ new Set();
      for (const selfRef of baseJs.matchAll(
        /([A-Za-z0-9$_]+)\[[A-Za-z0-9$_]+\^\d+\]=\1[,;]/g
      )) {
        if (nOut || typeof splitIdx !== "number" || splitIdx < 0) break;
        const fnDef = [
          ...baseJs.slice(0, selfRef.index).matchAll(/([A-Za-z0-9$_]+)=function\(/g)
        ].pop();
        if (!fnDef || tried.has(fnDef[1])) continue;
        const win = baseJs.slice(Math.max(0, selfRef.index - 2e3), selfRef.index);
        const accs = [...win.matchAll(splitRe)].filter((m) => m[1] === m[3]);
        if (!accs.length) continue;
        tried.add(fnDef[1]);
        const fn = fnDef[1];
        const Q = splitIdx ^ Number(accs[accs.length - 1][2]);
        const counts = {};
        for (let M = 0; M < 256; M++) {
          const r = ev(`${fn}(${M},${Q ^ M},${JSON.stringify(nIn)})`);
          if (validN(r, nIn)) counts[r] = (counts[r] || 0) + 1;
        }
        const ranked = Object.entries(counts).sort((a, b) => b[1] - a[1]);
        if (ranked.length && ranked[0][1] >= 3) nOut = ranked[0][0];
      }
    }
    if (!nOut) {
      const cand = /* @__PURE__ */ new Map();
      const nearestBefore = (v, end) => {
        const w = baseJs.slice(Math.max(0, end - 140), end);
        for (const [re, dec] of [
          [`${v}=([A-Za-z0-9$_]+(?:\\[\\d+\\])?)\\(${v}[,)]`, false],
          [`${v}=([A-Za-z0-9$_]+(?:\\[\\d+\\])?)\\(decodeURIComponent\\(${v}\\)`, true]
        ]) {
          const all = [...w.matchAll(new RegExp(re, "g"))];
          if (all.length) {
            const fn = all[all.length - 1][1];
            if (fn !== sigFn) cand.set(fn, dec);
          }
        }
      };
      for (const m of baseJs.matchAll(/\.set\(\s*"n"\s*,\s*(\w+)\s*\)/g))
        nearestBefore(m[1], m.index);
      for (const m of baseJs.matchAll(
        /\[([A-Za-z0-9$_]+)\[(\d+)\]\]\(\1\[(\d+)\],\s*(\w+)\)/g
      )) {
        const [, A, i, j, v] = m;
        if (ev(`${A}[${j}]`) === "n" && ev(`${A}[${i}]`) === "set")
          nearestBefore(v, m.index);
      }
      const probe = nIn.length > 1 ? nIn.slice(1) + nIn[0] : nIn + "A";
      for (const [fn, dec] of cand) {
        const call = (v) => ev(`${fn}(${dec ? `decodeURIComponent(${JSON.stringify(v)})` : JSON.stringify(v)})`);
        const r = call(nIn);
        if (validN(r, nIn) && call(probe) !== r) {
          nOut = r;
          break;
        }
      }
    }
    if (!nOut)
      throw new Error("n-challenge: no strategy matched (player structure changed)");
  }
  return { sig, n: nOut };
}
async function fetchAssets() {
  const s = getSession();
  if (!s) throw new Error("not authenticated");
  const html = await (await fetch(MUSIC_ORIGIN2 + "/", {
    headers: {
      Cookie: s.cookie,
      ...s.visitor_data ? { "X-Goog-Visitor-Id": s.visitor_data } : {},
      "Accept-Language": "en",
      "User-Agent": WEB_UA2
    }
  })).text();
  const clientVersion = html.match(/"INNERTUBE_CLIENT_VERSION":"([^"]+)"/)?.[1] ?? s.clientVersion ?? void 0;
  let jsUrl = html.match(/"jsUrl":"([^"]+)"/)?.[1];
  if (!clientVersion || !jsUrl)
    throw new Error("could not locate client version / jsUrl on home page");
  if (jsUrl.startsWith("/")) jsUrl = MUSIC_ORIGIN2 + jsUrl;
  const playerId = jsUrl.match(/\/player\/([^/]+)\//)?.[1] || "unknown";
  const baseJs = await (await fetch(jsUrl, { headers: { "User-Agent": WEB_UA2 } })).text();
  const sts = Number(baseJs.match(/signatureTimestamp:(\d+)/)?.[1]);
  if (!sts) throw new Error("could not read signatureTimestamp from base.js");
  const portal = makePortal(baseJs);
  return { playerId, baseJs, sts, clientVersion, portal };
}
async function getAssets() {
  if (assetsCache && assetsCache.expires > Date.now()) return assetsCache.assets;
  const assets = await fetchAssets();
  assetsCache = { assets, expires: Date.now() + ASSETS_TTL_MS };
  return assets;
}
async function callPremiumPlayer(videoId, assets) {
  const s = getSession();
  if (!s) throw new Error("not authenticated");
  const body = {
    context: {
      client: {
        clientName: "WEB_REMIX",
        clientVersion: assets.clientVersion,
        hl: "en",
        gl: "US",
        visitorData: s.visitor_data ?? void 0
      },
      user: {}
    },
    videoId,
    playbackContext: {
      contentPlaybackContext: {
        html5Preference: "HTML5_PREF_WANTS",
        signatureTimestamp: assets.sts
      }
    },
    contentCheckOk: true,
    racyCheckOk: true
  };
  const res = await fetch(
    `${MUSIC_ORIGIN2}/youtubei/v1/player?prettyPrint=false${s.apiKey ? `&key=${s.apiKey}` : ""}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Cookie: s.cookie,
        Authorization: sapisidAuth2(s.cookie),
        Origin: MUSIC_ORIGIN2,
        "X-Origin": MUSIC_ORIGIN2,
        Referer: MUSIC_ORIGIN2 + "/",
        "X-Goog-AuthUser": "0",
        ...s.visitor_data ? { "X-Goog-Visitor-Id": s.visitor_data } : {},
        "X-Youtube-Client-Name": "67",
        "X-Youtube-Client-Version": assets.clientVersion,
        "User-Agent": WEB_UA2
      },
      body: JSON.stringify(body)
    }
  );
  if (!res.ok) throw new Error(`premium player ${res.status}: ${await res.text()}`);
  return res.json();
}
async function getPlayer(videoId) {
  const assets = await getAssets();
  const hit = playerCache.get(videoId);
  if (hit && hit.expires > Date.now()) return { player: hit.player, assets };
  const player = await callPremiumPlayer(videoId, assets);
  playerCache.set(videoId, { player, expires: Date.now() + PLAYER_TTL_MS });
  return { player, assets };
}
function audioFormats(player) {
  return (player?.streamingData?.adaptiveFormats ?? []).filter(
    (f) => String(f.mimeType).startsWith("audio/")
  );
}
function pickPremium(player) {
  const byItag = new Map(audioFormats(player).map((f) => [f.itag, f]));
  for (const t of PREMIUM_ITAGS) if (byItag.has(t)) return byItag.get(t);
  return null;
}
function pickAudio(player, hq) {
  if (hq) {
    const premium = pickPremium(player);
    if (premium) return premium;
  }
  const formats = audioFormats(player);
  const pool = hq ? formats : formats.filter((f) => !PREMIUM_ITAGS.includes(f.itag));
  return (pool.length ? pool : formats).sort((a, b) => (b.bitrate ?? 0) - (a.bitrate ?? 0))[0] ?? null;
}
function decoratorName(assets) {
  if (assets.decorator !== void 0) return assets.decorator;
  const js = assets.baseJs;
  const sig = js.match(
    /(?<![.\w$])([A-Za-z0-9$_]+)=function\((\w+)[^)]*\)\{\2=new [\w.$]+\(\2,\s*!0[,)][^]{0,40}?\.set\("alr","yes"\)/
  );
  let name = sig ? sig[1] : null;
  if (!name) {
    const at = js.search(/"alr"\s*,\s*"yes"/);
    const head = at < 0 ? null : [...js.slice(0, at).matchAll(/\b([A-Za-z0-9$_]+)=function\(/g)].pop();
    name = head ? head[1] : null;
  }
  assets.decorator = name;
  return assets.decorator;
}
function solveViaDecorator(assets, dec, s, nIn) {
  const expr = `(function(){var u=${dec}("https://youtube.com/watch?v=yt-dlp-wins","s",encodeURIComponent(${JSON.stringify(s)}));` + (nIn ? `u.set("n",${JSON.stringify(nIn)});` : ``) + `var p=Object.getPrototypeOf(u),ks=Object.keys(p).concat(Object.getOwnPropertyNames(p));for(var i=0;i<ks.length;i++){var k=ks[i];if(["constructor","set","get","clone"].indexOf(k)<0){u[k]();break}}var ss=u.get("s");return {sig:ss?decodeURIComponent(ss):null,n:u.get("n")}})()`;
  const out = assets.portal.evT(expr, 3e3);
  if (!out || typeof out.sig !== "string") return null;
  return { sig: out.sig, n: typeof out.n === "string" ? out.n : null };
}
async function streamsOk(url) {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), 7e3);
  try {
    const r = await fetch(url, { headers: { Range: "bytes=0-1" }, signal: ctrl.signal });
    if (r.body) await r.body.cancel().catch(() => {
    });
    return r.status === 200 || r.status === 206;
  } catch {
    return false;
  } finally {
    clearTimeout(t);
  }
}
function buildUrl(baseUrl, sp, sig, n) {
  const u = new URL(baseUrl);
  u.searchParams.set(sp, sig);
  if (n) u.searchParams.set("n", n);
  return u.toString();
}
async function resolvedUrl(fmt, assets) {
  if (fmt.url) return fmt.url;
  const cipher = new URLSearchParams(fmt.signatureCipher);
  const baseUrl = cipher.get("url");
  if (!baseUrl) throw new Error("no url/signatureCipher");
  const sp = cipher.get("sp") || "sig";
  const s = cipher.get("s");
  if (!s) throw new Error("no signature in cipher");
  const nIn = new URL(baseUrl).searchParams.get("n");
  const dec = decoratorName(assets);
  let decUrl = null;
  if (dec) {
    const sol = solveViaDecorator(assets, dec, s, nIn);
    if (sol && sol.sig && (!nIn || sol.n)) {
      decUrl = buildUrl(baseUrl, sp, sol.sig, sol.n);
      if (assets.decoratorOk) return decUrl;
      if (await streamsOk(decUrl)) {
        assets.decoratorOk = true;
        return decUrl;
      }
    }
  }
  try {
    const { sig, n } = descramble(assets.baseJs, assets.portal, s, nIn);
    return buildUrl(baseUrl, sp, sig, n);
  } catch (e) {
    if (decUrl) return decUrl;
    throw e;
  }
}
async function resolvePremiumAudio(videoId) {
  const { player, assets } = await getPlayer(videoId);
  const status = player?.playabilityStatus?.status;
  if (status !== "OK")
    throw new Error(`premium: ${player?.playabilityStatus?.reason || status}`);
  const fmt = pickPremium(player);
  if (!fmt) throw new Error("no premium format (itag 141/774)");
  return {
    itag: fmt.itag,
    url: await resolvedUrl(fmt, assets),
    mimeType: fmt.mimeType,
    bitrate: fmt.bitrate ?? 0,
    contentLength: fmt.contentLength
  };
}
async function resolveAuthedAudio(videoId, hq) {
  const { player, assets } = await getPlayer(videoId);
  const status = player?.playabilityStatus?.status;
  if (status !== "OK")
    throw new Error(`authed: ${player?.playabilityStatus?.reason || status}`);
  const fmt = pickAudio(player, hq);
  if (!fmt) throw new Error("authed: no audio format");
  return {
    itag: fmt.itag,
    url: await resolvedUrl(fmt, assets),
    mimeType: fmt.mimeType,
    bitrate: fmt.bitrate ?? 0,
    contentLength: fmt.contentLength
  };
}
function buildStreamInfo(videoId, player, f) {
  const mime = f.mimeType ?? "";
  const container = mime.split(";")[0]?.split("/")[1] ?? null;
  const codec = /codecs="([^"]+)"/.exec(mime)?.[1] ?? null;
  return {
    videoId,
    itag: f.itag ?? null,
    codec,
    container,
    bitrate: f.bitrate ?? null,
    averageBitrate: f.averageBitrate ?? null,
    audioSampleRate: f.audioSampleRate ?? null,
    audioChannels: f.audioChannels ?? null,
    contentLength: f.contentLength ?? null,
    loudnessDb: player?.playerConfig?.audioConfig?.loudnessDb ?? null,
    client: "WEB_REMIX"
  };
}
async function premiumStreamInfo(videoId) {
  const { player, assets } = await getPlayer(videoId);
  const status = player?.playabilityStatus?.status;
  if (status !== "OK")
    throw new Error(`premium: ${player?.playabilityStatus?.reason || status}`);
  const f = pickPremium(player);
  if (!f) throw new Error("no premium format (itag 141/774)");
  await resolvedUrl(f, assets);
  return buildStreamInfo(videoId, player, f);
}
async function authedStreamInfo(videoId, hq) {
  const { player } = await getPlayer(videoId);
  const status = player?.playabilityStatus?.status;
  if (status !== "OK")
    throw new Error(`authed: ${player?.playabilityStatus?.reason || status}`);
  const f = pickAudio(player, hq);
  if (!f) throw new Error("authed: no audio format");
  return buildStreamInfo(videoId, player, f);
}

// server/parse.ts
function findOne(o, key) {
  if (o == null || typeof o !== "object") return null;
  if (key in o) return o[key];
  for (const k of Object.keys(o)) {
    const r = findOne(o[k], key);
    if (r) return r;
  }
  return null;
}
function findAll(o, key, out = []) {
  if (o == null || typeof o !== "object") return out;
  if (Array.isArray(o)) {
    for (const e of o) findAll(e, key, out);
    return out;
  }
  for (const k of Object.keys(o)) {
    if (k === key) out.push(o[k]);
    else findAll(o[k], key, out);
  }
  return out;
}
function text(node) {
  if (!node) return null;
  if (typeof node === "string") return node;
  if (node.simpleText != null) return node.simpleText;
  if (Array.isArray(node.runs)) return node.runs.map((r) => r.text).join("");
  return null;
}
function hiRes(url) {
  if (!url) return url;
  return url.replace(/=(?:w\d+-h\d+|s\d+)(?:-[a-z0-9]+)*$/i, "");
}
function thumb(node) {
  const t = findOne(node, "thumbnails");
  if (!Array.isArray(t) || !t.length) return null;
  return hiRes(t[t.length - 1].url ?? null);
}
function endpoint(node) {
  const we = findOne(node, "watchEndpoint");
  const be = findOne(node, "browseEndpoint");
  return {
    videoId: we?.videoId,
    playlistId: we?.playlistId,
    browseId: be?.browseId,
    pageType: be?.browseEndpointContextSupportedConfigs?.browseEndpointContextMusicConfig?.pageType
  };
}
function menuExtras(node) {
  const menu = findOne(node, "menuRenderer");
  const out = {
    channelId: null,
    albumBrowseId: null,
    libraryAddToken: null,
    libraryRemoveToken: null,
    inLibrary: false,
    entityId: findOne(node, "entityId") ?? null
  };
  if (!menu) return out;
  for (const item of findAll(menu, "menuNavigationItemRenderer")) {
    const be = item?.navigationEndpoint?.browseEndpoint;
    const pt = be?.browseEndpointContextSupportedConfigs?.browseEndpointContextMusicConfig?.pageType;
    if (pt === "MUSIC_PAGE_TYPE_ARTIST" && !out.channelId) out.channelId = be.browseId ?? null;
    else if (pt === "MUSIC_PAGE_TYPE_ALBUM" && !out.albumBrowseId) out.albumBrowseId = be.browseId ?? null;
  }
  for (const tg of findAll(menu, "toggleMenuServiceItemRenderer")) {
    const def = text(tg.defaultText) ?? "";
    const tog = text(tg.toggledText) ?? "";
    if (!/mediathek|library/i.test(def) && !/mediathek|library/i.test(tog)) continue;
    const defTok = findOne(tg.defaultServiceEndpoint, "feedbackToken");
    const togTok = findOne(tg.toggledServiceEndpoint, "feedbackToken");
    const inLib = /entfernen|remove/i.test(def);
    out.inLibrary = inLib;
    out.libraryAddToken = inLib ? togTok ?? null : defTok ?? null;
    out.libraryRemoveToken = inLib ? defTok ?? null : togTok ?? null;
    break;
  }
  return out;
}
function flexText(col) {
  return col?.musicResponsiveListItemFlexColumnRenderer?.text;
}
function isExplicit(node) {
  const badge = findOne(node, "musicInlineBadgeRenderer");
  const label = badge?.accessibilityData?.accessibilityData?.label || "";
  return /explicit/i.test(label);
}
function parseSongRow(r) {
  const ep = endpoint(
    findOne(r, "musicPlayButtonRenderer")?.playNavigationEndpoint ?? r
  );
  const videoId = ep.videoId;
  if (!videoId) return null;
  const cols = r.flexColumns ?? [];
  const title = text(flexText(cols[0]));
  const subRuns = flexText(cols[1])?.runs ?? [];
  const named = subRuns.filter((x) => x.text && x.text.trim() !== "\u2022" && x.text.trim());
  const artists = [];
  let album2 = null;
  let duration = null;
  for (const run of named) {
    const t = run.text.trim();
    if (/^\d+:\d{2}$/.test(t)) duration = t;
    else if (run.navigationEndpoint) {
      const pt = endpoint(run.navigationEndpoint).pageType;
      if (pt === "MUSIC_PAGE_TYPE_ALBUM") album2 = t;
      else artists.push(t);
    }
  }
  if (!duration) {
    const fixed = r.fixedColumns?.[0];
    duration = text(fixed?.musicResponsiveListItemFixedColumnRenderer?.text);
  }
  const secs = duration ? duration.split(":").reduce((a, b) => a * 60 + Number(b), 0) : null;
  return {
    videoId,
    title,
    artist: artists.join(", "),
    album: album2,
    duration,
    durationSeconds: secs,
    thumbnail: thumb(r),
    setVideoId: r.playlistItemData?.playlistSetVideoId ?? null,
    ...menuExtras(r)
  };
}
function parseCard(r) {
  const thumbnail = thumb(r);
  const ep = endpoint(r.navigationEndpoint ?? r);
  const title = text(r.title);
  const subtitle = text(r.subtitle);
  const explicit = isExplicit(r);
  const wide = /16_9|RECTANGLE/.test(r.aspectRatio || "");
  if (ep.videoId) {
    return {
      kind: "video",
      videoId: ep.videoId,
      title,
      subtitle,
      thumbnail,
      aspect: wide ? "video" : "square",
      explicit
    };
  }
  const isAlbum = ep.pageType === "MUSIC_PAGE_TYPE_ALBUM";
  return {
    kind: isAlbum ? "album" : "playlist",
    browseId: ep.browseId ?? null,
    playlistId: ep.playlistId ?? (ep.browseId?.startsWith("VL") ? ep.browseId.slice(2) : null),
    title,
    subtitle,
    thumbnail,
    aspect: "square",
    explicit
  };
}
function parseTracks(resp) {
  const rows = findAll(resp, "musicResponsiveListItemRenderer");
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const r of rows) {
    const t = parseSongRow(r);
    if (t && !seen.has(t.videoId)) {
      seen.add(t.videoId);
      out.push(t);
    }
  }
  return out;
}
function argbToHex(n) {
  if (typeof n !== "number") return null;
  const hex = (n & 16777215).toString(16).padStart(6, "0");
  return `#${hex}`;
}
function parseChip(b) {
  const label = text(b?.buttonText);
  const ep = b?.clickCommand?.browseEndpoint;
  if (!label || !ep?.browseId) return null;
  return {
    text: label,
    browseId: ep.browseId,
    params: ep.params ?? null,
    color: argbToHex(b?.solid?.leftStripeColor),
    icon: b?.iconStyle?.icon?.iconType ?? null
  };
}
function cardFromSongRow(r) {
  const t = parseSongRow(r);
  if (!t || !t.thumbnail) return null;
  return {
    kind: "video",
    videoId: t.videoId,
    title: t.title,
    subtitle: t.artist || null,
    thumbnail: t.thumbnail,
    aspect: "square",
    explicit: false
  };
}
function shelfTitle(shelf) {
  return text(
    shelf?.header?.musicCarouselShelfBasicHeaderRenderer?.title ?? shelf?.header?.gridHeaderRenderer?.title ?? shelf?.title ?? findOne(shelf?.header, "title")
  );
}
function shelfMore(shelf) {
  const be = findOne(shelf?.header, "browseEndpoint");
  return be?.browseId ? { browseId: be.browseId, params: be.params ?? null } : null;
}
function shelfCards(shelf) {
  const cards = [];
  for (const it of findAll(shelf, "musicTwoRowItemRenderer")) {
    const c = parseCard(it);
    if (c && c.thumbnail) cards.push(c);
  }
  for (const r of findAll(shelf, "musicResponsiveListItemRenderer")) {
    const c = cardFromSongRow(r);
    if (c) cards.push(c);
  }
  return cards;
}
function parseHome(resp, limit = 12) {
  const sections = [];
  for (const sl of findAll(resp, "sectionListRenderer")) {
    if (Array.isArray(sl?.contents)) sections.push(...sl.contents);
  }
  for (const ci of findAll(resp, "continuationItems")) {
    if (Array.isArray(ci)) sections.push(...ci);
  }
  const shelves = [];
  const seen = /* @__PURE__ */ new Set();
  for (const sec of sections) {
    const shelf = sec.musicCarouselShelfRenderer ?? sec.musicImmersiveCarouselShelfRenderer ?? sec.gridRenderer ?? sec.musicShelfRenderer;
    if (!shelf) continue;
    const title = shelfTitle(shelf);
    const cards = shelfCards(shelf);
    if (!cards.length) {
      const chips = findAll(shelf, "musicNavigationButtonRenderer").map(parseChip).filter((c) => !!c);
      if (!chips.length) continue;
      const key2 = `${title ?? ""}|${chips[0].browseId}|${chips[0].params ?? ""}`;
      if (seen.has(key2)) continue;
      seen.add(key2);
      shelves.push({ title, cards: [], chips });
      if (shelves.length >= limit) break;
      continue;
    }
    const key = `${title ?? ""}|${cards[0].videoId ?? cards[0].browseId ?? cards[0].playlistId ?? ""}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const more = shelfMore(shelf);
    shelves.push({ title, cards, moreBrowseId: more?.browseId ?? null, moreParams: more?.params ?? null });
    if (shelves.length >= limit) break;
  }
  return shelves;
}
function parseLibraryPlaylists(resp) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const r of findAll(resp, "musicTwoRowItemRenderer")) {
    const ep = endpoint(r.navigationEndpoint ?? r);
    const pid = ep.playlistId ?? (ep.browseId?.startsWith("VL") ? ep.browseId.slice(2) : ep.browseId);
    if (!pid || ep.pageType === "MUSIC_PAGE_TYPE_ARTIST" || ep.pageType === "MUSIC_PAGE_TYPE_USER_CHANNEL") continue;
    if (seen.has(pid)) continue;
    seen.add(pid);
    out.push({
      playlistId: pid,
      title: text(r.title),
      thumbnail: thumb(r),
      count: text(r.subtitle)
    });
  }
  return out;
}
function parsePlaylist(resp) {
  const h = findOne(resp, "musicResponsiveHeaderRenderer") ?? findOne(resp, "musicEditablePlaylistDetailHeaderRenderer") ?? findOne(resp, "musicDetailHeaderRenderer");
  const facepile = findOne(h, "musicFacepileRenderer");
  const description = text(findOne(resp, "musicDescriptionShelfRenderer")?.description) ?? text(h?.description) ?? null;
  return {
    title: text(h?.title),
    owner: text(h?.straplineTextOne) ?? text(facepile?.text) ?? null,
    ownerThumbnail: thumb(h?.straplineThumbnail) ?? thumb(facepile) ?? null,
    subtitle: text(h?.subtitle),
    secondSubtitle: text(h?.secondSubtitle),
    description,
    thumbnail: thumb(h?.thumbnail),
    results: parseTracks(resp)
  };
}
function parseCards(resp) {
  return findAll(resp, "musicTwoRowItemRenderer").map(parseCard).filter((c) => !!c);
}
function parseSearchSuggestions(resp) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const s of findAll(resp, "searchSuggestionRenderer")) {
    const q = s?.navigationEndpoint?.searchEndpoint?.query ?? text(s?.suggestion);
    if (q && !seen.has(q)) {
      seen.add(q);
      out.push(q);
    }
  }
  return out;
}
function browseKindOf(pageType) {
  switch (pageType) {
    case "MUSIC_PAGE_TYPE_ALBUM":
      return "album";
    case "MUSIC_PAGE_TYPE_ARTIST":
    case "MUSIC_PAGE_TYPE_USER_CHANNEL":
    case "MUSIC_PAGE_TYPE_LIBRARY_ARTIST":
      return "artist";
    case "MUSIC_PAGE_TYPE_PLAYLIST":
      return "playlist";
    default:
      return null;
  }
}
function parseSearchItems(resp) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const r of findAll(resp, "musicResponsiveListItemRenderer")) {
    const cols = r.flexColumns ?? [];
    const title = text(flexText(cols[0]));
    const subtitle = text(flexText(cols[1]));
    const explicit = isExplicit(r);
    const navEp = r.navigationEndpoint ? endpoint(r.navigationEndpoint) : {};
    const browseKind = browseKindOf(navEp.pageType);
    if (navEp.browseId && browseKind) {
      if (seen.has("b:" + navEp.browseId)) continue;
      seen.add("b:" + navEp.browseId);
      out.push({
        kind: browseKind,
        browseId: navEp.browseId,
        playlistId: navEp.browseId.startsWith("VL") ? navEp.browseId.slice(2) : navEp.playlistId ?? null,
        title,
        subtitle,
        thumbnail: thumb(r),
        duration: null,
        explicit
      });
      continue;
    }
    const videoId = endpoint(findOne(r, "musicPlayButtonRenderer")?.playNavigationEndpoint ?? {}).videoId ?? navEp.videoId;
    if (!videoId) continue;
    if (seen.has("v:" + videoId)) continue;
    seen.add("v:" + videoId);
    const subRuns = flexText(cols[1])?.runs ?? [];
    let duration = subRuns.map((x) => x.text?.trim()).find((t) => /^\d+:\d{2}$/.test(t || "")) ?? null;
    if (!duration) {
      const fixed = r.fixedColumns?.[0];
      duration = text(fixed?.musicResponsiveListItemFixedColumnRenderer?.text);
    }
    out.push({ kind: "song", videoId, title, subtitle, thumbnail: thumb(r), duration, explicit, ...menuExtras(r) });
  }
  return out;
}
function parseArtist(resp) {
  const header = findOne(resp, "musicImmersiveHeaderRenderer") ?? findOne(resp, "musicVisualHeaderRenderer");
  const sub = findOne(header, "subscribeButtonRenderer");
  const topShelf = findOne(resp, "musicShelfRenderer");
  return {
    name: text(header?.title),
    thumbnail: thumb(header),
    subscribers: text(sub?.subscriberCountText),
    channelId: sub?.channelId ?? null,
    subscribed: !!sub?.subscribed,
    description: text(findOne(resp, "musicDescriptionShelfRenderer")?.description),
    songs: topShelf ? parseTracks(topShelf) : [],
    shelves: parseHome(resp, 20)
  };
}
function parseAlbum(resp) {
  const h = findOne(resp, "musicResponsiveHeaderRenderer") ?? findOne(resp, "musicDetailHeaderRenderer") ?? findOne(resp, "musicEditablePlaylistDetailHeaderRenderer");
  return {
    title: text(h?.title),
    artist: text(h?.straplineTextOne),
    subtitle: text(h?.subtitle),
    secondSubtitle: text(h?.secondSubtitle),
    thumbnail: thumb(h),
    tracks: parseTracks(resp)
  };
}
function parsePanelVideo(n) {
  const videoId = n?.videoId ?? endpoint(n?.navigationEndpoint ?? {}).videoId;
  if (!videoId) return null;
  const runs = n?.longBylineText?.runs ?? [];
  const artists = runs.filter((r) => r?.navigationEndpoint && endpoint(r.navigationEndpoint).pageType === "MUSIC_PAGE_TYPE_ARTIST").map((r) => r.text);
  const artist2 = artists.length ? artists.join(", ") : runs[0]?.text ?? "";
  const duration = text(n?.lengthText);
  const secs = duration ? duration.split(":").reduce((a, b) => a * 60 + Number(b), 0) : null;
  return {
    videoId,
    title: text(n?.title),
    artist: artist2,
    album: null,
    duration,
    durationSeconds: secs,
    thumbnail: thumb(n),
    ...menuExtras(n)
  };
}
function queueToken(resp) {
  const radio2 = findOne(resp, "nextRadioContinuationData")?.continuation;
  if (radio2) return radio2;
  const legacy = findOne(resp, "nextContinuationData")?.continuation;
  if (legacy) return legacy;
  for (const c of findAll(resp, "continuationCommand")) if (c?.token) return c.token;
  return null;
}
var VIDEO_MARKER = /[([][^)\]]*\b(?:official|video|lyric|lyrics|audio|visuali\w*|clip|mv|hd|4k|hq)\b[^)\]]*[)\]]/g;
function songKey(title) {
  return (title ?? "").toLowerCase().replace(VIDEO_MARKER, " ").replace(/[([][^)\]]*$/, " ").replace(/[^a-z0-9]+/g, " ").trim();
}
function parseQueue(resp) {
  const tracks = [];
  const chosenAtv = [];
  const idxByKey = /* @__PURE__ */ new Map();
  for (const n of findAll(resp, "playlistPanelVideoRenderer")) {
    const t = parsePanelVideo(n);
    if (!t) continue;
    const atv = findOne(n, "watchEndpointMusicConfig")?.musicVideoType === "MUSIC_VIDEO_TYPE_ATV";
    const key = t.title ? songKey(t.title) : t.videoId;
    const at = idxByKey.get(key);
    if (at == null) {
      idxByKey.set(key, tracks.length);
      tracks.push(t);
      chosenAtv.push(atv);
    } else if (atv && !chosenAtv[at]) {
      tracks[at] = t;
      chosenAtv[at] = true;
    }
  }
  let relatedBrowseId = null;
  let lyricsBrowseId = null;
  for (const tb of findAll(resp, "tabRenderer")) {
    const be = tb?.endpoint?.browseEndpoint;
    const pt = be?.browseEndpointContextSupportedConfigs?.browseEndpointContextMusicConfig?.pageType;
    if (pt === "MUSIC_PAGE_TYPE_TRACK_RELATED") relatedBrowseId = be.browseId;
    else if (pt === "MUSIC_PAGE_TYPE_TRACK_LYRICS") lyricsBrowseId = be.browseId;
  }
  return { tracks, continuation: queueToken(resp), relatedBrowseId, lyricsBrowseId };
}
function parseRelated(resp) {
  return { tracks: parseTracks(resp), shelves: parseHome(resp, 20) };
}
function parseHistory(resp) {
  const out = [];
  for (const sh of findAll(resp, "musicShelfRenderer")) {
    const tracks = parseTracks(sh);
    if (tracks.length) out.push({ title: text(sh.title), tracks });
  }
  return out;
}
function parseGrid(resp) {
  const title = text(
    findOne(resp, "gridHeaderRenderer")?.title ?? findOne(resp, "musicHeaderRenderer")?.title ?? findOne(resp, "header")?.title
  );
  return { title, cards: parseCards(resp) };
}
function parseLibraryArtists(resp) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const r of findAll(resp, "musicResponsiveListItemRenderer")) {
    const ep = endpoint(r.navigationEndpoint ?? r);
    if (!ep.browseId || !browseKindOf(ep.pageType)) continue;
    if (browseKindOf(ep.pageType) !== "artist") continue;
    if (seen.has(ep.browseId)) continue;
    seen.add(ep.browseId);
    const cols = r.flexColumns ?? [];
    out.push({
      browseId: ep.browseId,
      name: text(flexText(cols[0])),
      subtitle: text(flexText(cols[1])),
      thumbnail: thumb(r)
    });
  }
  return out;
}
function parseTasteProfile(resp) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const it of findAll(resp, "tastebuilderItemRenderer")) {
    const name = text(it?.title);
    if (!name || seen.has(name)) continue;
    seen.add(name);
    out.push({
      name,
      selectionValue: it?.selectionFormValue ?? null,
      impressionValue: it?.impressionValue ?? null,
      thumbnail: thumb(it)
    });
  }
  return out;
}
function parseEpisodeRow(n) {
  const onTap = n?.onTap ?? n?.navigationEndpoint ?? n;
  return {
    videoId: findOne(onTap, "videoId") ?? n?.videoId ?? null,
    title: text(n?.title),
    description: text(n?.description) ?? text(findOne(n, "musicMultilineTextRenderer")),
    date: text(n?.subtitle),
    duration: text(findOne(n, "lengthText")),
    thumbnail: thumb(n)
  };
}
function parsePodcast(resp) {
  const h = findOne(resp, "musicResponsiveHeaderRenderer") ?? findOne(resp, "musicDetailHeaderRenderer");
  return {
    title: text(h?.title),
    author: text(h?.straplineTextOne) ?? text(h?.subtitle),
    description: text(findOne(resp, "musicDescriptionShelfRenderer")?.description) ?? text(h?.description),
    thumbnail: thumb(h),
    episodes: findAll(resp, "musicMultiRowListItemRenderer").map(parseEpisodeRow)
  };
}
function parseEpisode(resp) {
  const row = findAll(resp, "musicMultiRowListItemRenderer")[0];
  if (row) return parseEpisodeRow(row);
  const h = findOne(resp, "musicResponsiveHeaderRenderer") ?? findOne(resp, "musicDetailHeaderRenderer");
  return {
    videoId: findOne(resp, "videoId") ?? null,
    title: text(h?.title),
    description: text(findOne(resp, "musicDescriptionShelfRenderer")?.description) ?? text(h?.description),
    date: text(h?.subtitle),
    duration: null,
    thumbnail: thumb(h)
  };
}
function parseSearchSuggestionsDetailed(resp) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const s of findAll(resp, "searchSuggestionRenderer")) {
    const q = s?.navigationEndpoint?.searchEndpoint?.query ?? text(s?.suggestion);
    if (!q || seen.has(q)) continue;
    seen.add(q);
    const removeToken = findOne(s, "feedbackToken");
    out.push({ query: q, fromHistory: !!removeToken, removeToken: removeToken ?? null });
  }
  return out;
}

// server/ytm.ts
var SONGS_PARAMS = "EgWKAQIIAWoKEAkQBRAKEAMQBA==";
var FILTER_PARAMS = {
  songs: SONGS_PARAMS,
  videos: "EgWKAQIQAWoKEAkQChAFEAMQBA==",
  albums: "EgWKAQIYAWoKEAkQChAFEAMQBA==",
  artists: "EgWKAQIgAWoKEAkQChAFEAMQBA==",
  playlists: "EgWKAQIoAWoKEAkQChAFEAMQBA=="
};
async function search(q) {
  if (!q.trim()) return [];
  const resp = await callMusic("search", { query: q, params: SONGS_PARAMS });
  return parseTracks(resp);
}
async function searchItems(q, filter = "songs") {
  if (!q.trim()) return [];
  const params = FILTER_PARAMS[filter] ?? SONGS_PARAMS;
  return parseSearchItems(await callMusic("search", { query: q, params }));
}
async function searchSuggestions(input) {
  if (!input.trim()) return [];
  return parseSearchSuggestions(
    await callMusic("music/get_search_suggestions", { input })
  );
}
async function searchSuggestionsDetailed(input) {
  if (!input.trim()) return [];
  return parseSearchSuggestionsDetailed(
    await callMusic("music/get_search_suggestions", { input })
  );
}
async function removeSearchSuggestions(tokens) {
  const valid2 = tokens.filter(Boolean);
  if (!valid2.length) return;
  await callMusic("feedback", { feedbackTokens: valid2 });
}
function continuationToken(resp) {
  const legacy = findOne(resp, "nextContinuationData")?.continuation;
  if (legacy) return legacy;
  const items = findAll(resp, "continuationItemRenderer");
  for (const it of items) {
    const tok = it?.continuationEndpoint?.continuationCommand?.token;
    if (tok) return tok;
  }
  return null;
}
async function home(limit = 12) {
  let resp = await callMusic("browse", { browseId: "FEmusic_home" });
  const shelves = parseHome(resp, limit);
  let token = continuationToken(resp);
  let guard = 0;
  while (token && shelves.length < limit && guard++ < 10) {
    resp = await callMusic("browse", { continuation: token });
    shelves.push(...parseHome(resp, limit - shelves.length));
    token = continuationToken(resp);
  }
  return shelves.slice(0, limit);
}
async function newReleases() {
  return parseCards(await callMusic("browse", { browseId: "FEmusic_new_releases_albums" }));
}
async function tasteProfile() {
  return parseTasteProfile(await callMusic("browse", { browseId: "FEmusic_tastebuilder" }));
}
async function setTasteProfile(selections) {
  const valid2 = selections.filter((s) => s.selectionValue && s.impressionValue);
  if (!valid2.length) return;
  await callMusic("browse", {
    browseId: "FEmusic_tastebuilder",
    formData: { selectedValues: valid2.map((s) => s.selectionValue) },
    // The impression values are echoed back so YT knows which were shown.
    tasteProfileSelections: valid2
  });
}
async function explore(limit = 12) {
  let resp = await callMusic("browse", { browseId: "FEmusic_explore" });
  const shelves = parseHome(resp, limit);
  let token = continuationToken(resp);
  let guard = 0;
  while (token && shelves.length < limit && guard++ < 10) {
    resp = await callMusic("browse", { continuation: token });
    shelves.push(...parseHome(resp, limit - shelves.length));
    token = continuationToken(resp);
  }
  return shelves.slice(0, limit);
}
async function category(browseId, params) {
  const body = { browseId };
  if (params) body.params = params;
  return parseHome(await callMusic("browse", body), 30);
}
async function charts(limit = 12) {
  return parseHome(await callMusic("browse", { browseId: "FEmusic_charts" }), limit);
}
async function moods(limit = 30) {
  return parseHome(await callMusic("browse", { browseId: "FEmusic_moods_and_genres" }), limit);
}
function browseIdFor(playlistId) {
  return playlistId.startsWith("VL") ? playlistId : `VL${playlistId}`;
}
async function playlist(id) {
  const resp = await callMusic("browse", { browseId: browseIdFor(id) });
  return parsePlaylist(resp);
}
async function libraryPlaylists() {
  const resp = await callMusic("browse", { browseId: "FEmusic_liked_playlists" });
  return parseLibraryPlaylists(resp);
}
async function likedSongs() {
  const resp = await callMusic("browse", { browseId: "VLLM" });
  return parseTracks(resp);
}
async function artist(browseId) {
  return parseArtist(await callMusic("browse", { browseId }));
}
async function album(browseId) {
  return parseAlbum(await callMusic("browse", { browseId }));
}
async function artistAlbums(browseId, params) {
  const body = { browseId };
  if (params) body.params = params;
  return parseGrid(await callMusic("browse", body));
}
async function user(channelId) {
  return parseArtist(await callMusic("browse", { browseId: channelId }));
}
async function song(videoId) {
  return songDetails(videoId);
}
async function albumBrowseId(audioPlaylistId) {
  return resolveAlbumBrowseId(audioPlaylistId);
}
async function podcast(browseId) {
  return parsePodcast(await callMusic("browse", { browseId }));
}
async function episode(browseId) {
  return parseEpisode(await callMusic("browse", { browseId }));
}
async function channel(browseId) {
  return parseArtist(await callMusic("browse", { browseId }));
}
async function episodesPlaylist(playlistId = "SE") {
  const id = playlistId.startsWith("VL") ? playlistId : `VL${playlistId}`;
  return parsePlaylist(await callMusic("browse", { browseId: id }));
}
async function upNext(videoId, playlistId) {
  const body = { videoId };
  if (playlistId) body.playlistId = playlistId;
  return parseQueue(await callMusic("next", body));
}
async function related(browseId) {
  return parseRelated(await callMusic("browse", { browseId }));
}
async function radio(videoId) {
  return parseQueue(await callMusic("next", { videoId, playlistId: `RDAMVM${videoId}` }));
}
async function queueMore(continuation) {
  return parseQueue(await callMusic("next", { continuation }));
}
async function similar(videoId) {
  const q = parseQueue(await callMusic("next", { videoId }));
  if (!q.relatedBrowseId) return [];
  return parseRelated(await callMusic("browse", { browseId: q.relatedBrowseId })).tracks;
}
async function rating(videoId) {
  const resp = await callMusic("next", { videoId });
  const status = findOne(resp, "likeButtonRenderer")?.likeStatus;
  return status === "LIKE" || status === "DISLIKE" ? status : "INDIFFERENT";
}
async function librarySongs() {
  return parseTracks(await callMusic("browse", { browseId: "FEmusic_liked_videos" }));
}
async function libraryAlbums() {
  return parseCards(await callMusic("browse", { browseId: "FEmusic_liked_albums" }));
}
async function libraryArtists() {
  return parseLibraryArtists(
    await callMusic("browse", { browseId: "FEmusic_library_corpus_track_artists" })
  );
}
async function history() {
  return parseHistory(await callMusic("browse", { browseId: "FEmusic_history" }));
}
async function librarySubscriptions() {
  return parseLibraryArtists(
    await callMusic("browse", { browseId: "FEmusic_library_corpus_artists" })
  );
}
async function libraryPodcasts() {
  return parseCards(await callMusic("browse", { browseId: "FEmusic_library_non_music_audio_list" }));
}
async function libraryUploadSongs() {
  return parseTracks(await callMusic("browse", { browseId: "FEmusic_library_privately_owned_tracks" }));
}
async function libraryUploadAlbums() {
  return parseCards(await callMusic("browse", { browseId: "FEmusic_library_privately_owned_releases" }));
}
async function libraryUploadArtists() {
  return parseLibraryArtists(
    await callMusic("browse", { browseId: "FEmusic_library_privately_owned_artists" })
  );
}
function rawPlaylistId(id) {
  return id.startsWith("VL") ? id.slice(2) : id;
}
async function rate(videoId, rating2) {
  const ep = rating2 === "LIKE" ? "like/like" : rating2 === "DISLIKE" ? "like/dislike" : "like/removelike";
  await callMusic(ep, { target: { videoId } });
}
async function ratePlaylist(playlistId, rating2) {
  const ep = rating2 === "LIKE" ? "like/like" : rating2 === "DISLIKE" ? "like/dislike" : "like/removelike";
  await callMusic(ep, { target: { playlistId: rawPlaylistId(playlistId) } });
}
async function addHistoryItem2(videoId) {
  await addHistoryItem(videoId);
}
async function removeHistoryItems(tokens) {
  const valid2 = tokens.filter(Boolean);
  if (!valid2.length) return;
  await callMusic("feedback", { feedbackTokens: valid2 });
}
async function deleteUploadEntity(entityId) {
  if (!entityId) return;
  await callMusic("music/delete_privately_owned_entity", { entityId });
}
async function uploadSong2(filePath) {
  return uploadSong(filePath);
}
async function feedback(tokens) {
  const valid2 = tokens.filter(Boolean);
  if (!valid2.length) return;
  await callMusic("feedback", { feedbackTokens: valid2 });
}
async function streamInfo2(videoId, hq = false) {
  if (hq) {
    try {
      return await premiumStreamInfo(videoId);
    } catch {
    }
  }
  try {
    return await authedStreamInfo(videoId, hq);
  } catch {
    return streamInfo(videoId);
  }
}
async function subscribe(channelId, on) {
  await callMusic(on ? "subscription/subscribe" : "subscription/unsubscribe", {
    channelIds: [channelId]
  });
}
async function createPlaylist(title, description = "", privacy = "PRIVATE") {
  const resp = await callMusic("playlist/create", {
    title,
    description,
    privacyStatus: privacy
  });
  return resp?.playlistId ?? findOne(resp, "playlistId") ?? null;
}
async function deletePlaylist(playlistId) {
  await callMusic("playlist/delete", { playlistId: rawPlaylistId(playlistId) });
}
async function addToPlaylist(playlistId, videoIds) {
  if (!videoIds.length) return;
  await callMusic("browse/edit_playlist", {
    playlistId: rawPlaylistId(playlistId),
    actions: videoIds.map((addedVideoId) => ({ action: "ACTION_ADD_VIDEO", addedVideoId }))
  });
}
async function removeFromPlaylist(playlistId, items) {
  if (!items.length) return;
  await callMusic("browse/edit_playlist", {
    playlistId: rawPlaylistId(playlistId),
    actions: items.map((i) => ({
      action: "ACTION_REMOVE_VIDEO",
      removedVideoId: i.videoId,
      setVideoId: i.setVideoId
    }))
  });
}
async function movePlaylistItem(playlistId, setVideoId, successorSetVideoId) {
  if (!setVideoId) return;
  const action = {
    action: "ACTION_MOVE_VIDEO_BEFORE",
    setVideoId
  };
  if (successorSetVideoId) action.movedSetVideoIdSuccessor = successorSetVideoId;
  await callMusic("browse/edit_playlist", {
    playlistId: rawPlaylistId(playlistId),
    actions: [action]
  });
}
async function renamePlaylist(playlistId, name) {
  await callMusic("browse/edit_playlist", {
    playlistId: rawPlaylistId(playlistId),
    actions: [{ action: "ACTION_SET_PLAYLIST_NAME", playlistName: name }]
  });
}
async function lyrics(videoId) {
  try {
    const next = await callMusic("next", { videoId });
    const tabs = findAll(next, "tabRenderer");
    const lyricsTab = tabs.find(
      (t) => t?.endpoint?.browseEndpoint?.browseEndpointContextSupportedConfigs?.browseEndpointContextMusicConfig?.pageType === "MUSIC_PAGE_TYPE_TRACK_LYRICS"
    );
    const browseId = lyricsTab?.endpoint?.browseEndpoint?.browseId;
    if (!browseId) return { text: null, source: null };
    const data = await callMusic("browse", { browseId });
    const shelf = findOne(data, "musicDescriptionShelfRenderer");
    return {
      text: text(shelf?.description),
      source: text(shelf?.footer)
    };
  } catch {
    return { text: null, source: null };
  }
}

// server/stream.ts
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
var cache = /* @__PURE__ */ new Map();
var TTL_MS = 30 * 60 * 1e3;
var CAPPED_CHUNK = 1 << 20;
async function resolveFormat(videoId, hq) {
  if (hq) {
    try {
      return await resolvePremiumAudio(videoId);
    } catch {
    }
  }
  try {
    return await resolveAuthedAudio(videoId, hq);
  } catch {
    return resolveAudio(videoId);
  }
}
async function resolveUrl(videoId, hq) {
  const key = `${hq ? "hq" : "lo"}:${videoId}`;
  const hit = cache.get(key);
  if (hit && hit.expires > Date.now()) return hit.url;
  const { url } = await resolveFormat(videoId, hq);
  cache.set(key, { url, expires: Date.now() + TTL_MS });
  return url;
}
function extFor(fmt) {
  if (fmt.mimeType.includes("audio/mp4")) return "m4a";
  if (fmt.mimeType.includes("audio/webm")) return "weba";
  return "audio";
}
function safeName(name) {
  return name.replace(/[\\/:*?"<>|]+/g, " ").replace(/\s+/g, " ").trim().slice(0, 120) || "audio";
}
async function pump(body, res) {
  if (!body) {
    res.end();
    return;
  }
  try {
    await pipeline(Readable.fromWeb(body), res);
  } catch {
    if (!res.destroyed) res.destroy();
  }
}
async function downloadAudio(videoId, name, res, hq = false) {
  let fmt;
  try {
    fmt = await resolveFormat(videoId, hq);
  } catch (e) {
    res.writeHead(502, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: `resolve failed: ${e}` }));
    return;
  }
  const upstream = await fetch(fmt.url);
  if (!upstream.ok) {
    await upstream.body?.cancel().catch(() => {
    });
    res.writeHead(502, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: `download failed: upstream ${upstream.status}` }));
    return;
  }
  const filename = `${safeName(name || videoId)}.${extFor(fmt)}`;
  const headers = {
    "Content-Type": fmt.mimeType.split(";")[0] || "application/octet-stream",
    "Content-Disposition": `attachment; filename="${filename}"`
  };
  const len = upstream.headers.get("content-length");
  if (len) headers["Content-Length"] = len;
  res.writeHead(upstream.status, headers);
  await pump(upstream.body, res);
}
async function streamAudio(videoId, req, res, hq = false) {
  let url;
  try {
    url = await resolveUrl(videoId, hq);
  } catch (e) {
    res.writeHead(502, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: `resolve failed: ${e}` }));
    return;
  }
  const range = req.headers["range"] ? String(req.headers["range"]) : null;
  let upstream = await fetch(url, { headers: range ? { Range: range } : {} });
  if (upstream.status === 403) {
    const start = range ? Number(/^bytes=(\d+)-$/.exec(range)?.[1]) : 0;
    if (Number.isFinite(start)) {
      await upstream.body?.cancel().catch(() => {
      });
      upstream = await fetch(url, {
        headers: { Range: `bytes=${start}-${start + CAPPED_CHUNK - 1}` }
      });
    }
  }
  const headers = { "Accept-Ranges": "bytes" };
  for (const k of ["content-type", "content-length", "content-range", "accept-ranges"]) {
    const v = upstream.headers.get(k);
    if (v) headers[k] = v;
  }
  res.writeHead(upstream.status, headers);
  await pump(upstream.body, res);
}

// server/account.ts
function txt(node) {
  return node?.runs?.map((r) => r.text).join("") ?? node?.simpleText ?? null;
}
function findAll2(o, key, out = []) {
  if (Array.isArray(o)) {
    for (const v of o) findAll2(v, key, out);
  } else if (o && typeof o === "object") {
    for (const [k, v] of Object.entries(o)) {
      if (k === key) out.push(v);
      findAll2(v, key, out);
    }
  }
  return out;
}
var EMPTY = { name: null, handle: null, photo: null };
var cache2 = null;
async function account() {
  const s = getSession();
  if (!s) return EMPTY;
  if (cache2 && cache2.sig === s.capturedAt) return cache2.data;
  const res = await fetch("https://www.youtube.com/getAccountSwitcherEndpoint", {
    headers: {
      Cookie: s.cookie,
      "X-Goog-AuthUser": "0",
      Referer: "https://www.youtube.com/",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36"
    }
  });
  if (!res.ok) return EMPTY;
  const j = JSON.parse((await res.text()).replace(/^\)\]\}'/, ""));
  const items = findAll2(j, "accountItem");
  const active = items.find((i) => i.isSelected) ?? items[0];
  if (!active) return EMPTY;
  const thumbs = findAll2(active, "thumbnails")[0] ?? [];
  let photo = thumbs[thumbs.length - 1]?.url ?? null;
  if (photo) photo = photo.replace(/=s\d+/, "=s176");
  const data = {
    name: txt(active.accountName),
    handle: findAll2(active, "channelHandle").map(txt).find(Boolean) ?? null,
    photo
  };
  cache2 = { sig: s.capturedAt, data };
  return data;
}

// server/api.ts
function sendJson(res, code, body) {
  const data = JSON.stringify(body);
  res.writeHead(code, { "Content-Type": "application/json" });
  res.end(data);
}
function readBody(req) {
  return new Promise((resolve) => {
    let data = "";
    req.on("data", (c) => data += c);
    req.on("end", () => {
      try {
        resolve(data ? JSON.parse(data) : {});
      } catch {
        resolve({});
      }
    });
  });
}
async function handle(req, res) {
  const url = new URL(req.url || "", "http://localhost");
  const p = url.pathname;
  if (!p.startsWith("/api/")) return false;
  const route = p.slice(4);
  const method = req.method || "GET";
  try {
    const hq = url.searchParams.get("hq") === "1";
    if (route.startsWith("/stream/")) {
      await streamAudio(decodeURIComponent(route.slice("/stream/".length)), req, res, hq);
      return true;
    }
    if (route.startsWith("/download/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/download/".length));
      const name = url.searchParams.get("name") || id;
      await downloadAudio(id, name, res, hq);
      return true;
    }
    if (route.startsWith("/player-info/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/player-info/".length));
      sendJson(res, 200, await streamInfo2(id, hq));
      return true;
    }
    if (route === "/home" && method === "GET") {
      sendJson(res, 200, { shelves: await home() });
      return true;
    }
    if (route === "/explore" && method === "GET") {
      sendJson(res, 200, { shelves: await explore() });
      return true;
    }
    if (route === "/charts" && method === "GET") {
      sendJson(res, 200, { shelves: await charts() });
      return true;
    }
    if (route === "/moods" && method === "GET") {
      sendJson(res, 200, { shelves: await moods() });
      return true;
    }
    if (route === "/new-releases" && method === "GET") {
      sendJson(res, 200, { results: await newReleases() });
      return true;
    }
    if (route === "/taste-profile" && method === "GET") {
      sendJson(res, 200, { artists: await tasteProfile() });
      return true;
    }
    if (route === "/category" && method === "GET") {
      const browseId = url.searchParams.get("browseId") || "";
      const params = url.searchParams.get("params") || void 0;
      sendJson(res, 200, { shelves: browseId ? await category(browseId, params) : [] });
      return true;
    }
    if (route === "/search" && method === "GET") {
      const q = url.searchParams.get("q") || "";
      const filter = url.searchParams.get("filter");
      if (filter) {
        sendJson(res, 200, { results: await searchItems(q, filter) });
      } else {
        sendJson(res, 200, { results: await search(q) });
      }
      return true;
    }
    if (route === "/suggest" && method === "GET") {
      const q = url.searchParams.get("q") || "";
      if (url.searchParams.get("detailed")) {
        sendJson(res, 200, { suggestions: await searchSuggestionsDetailed(q) });
      } else {
        sendJson(res, 200, { suggestions: await searchSuggestions(q) });
      }
      return true;
    }
    if (route.startsWith("/playlist/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/playlist/".length));
      sendJson(res, 200, await playlist(id));
      return true;
    }
    if (route.startsWith("/artist/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/artist/".length));
      sendJson(res, 200, await artist(id));
      return true;
    }
    if (route === "/artist-albums" && method === "GET") {
      const browseId = url.searchParams.get("browseId") || "";
      const params = url.searchParams.get("params") || void 0;
      sendJson(res, 200, browseId ? await artistAlbums(browseId, params) : { title: null, cards: [] });
      return true;
    }
    if (route.startsWith("/album/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/album/".length));
      sendJson(res, 200, await album(id));
      return true;
    }
    if (route === "/album-browse-id" && method === "GET") {
      const olak = url.searchParams.get("audioPlaylistId") || "";
      sendJson(res, 200, { browseId: olak ? await albumBrowseId(olak) : null });
      return true;
    }
    if (route.startsWith("/song/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/song/".length));
      sendJson(res, 200, await song(id));
      return true;
    }
    if (route.startsWith("/user/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/user/".length));
      sendJson(res, 200, await user(id));
      return true;
    }
    if (route.startsWith("/channel/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/channel/".length));
      sendJson(res, 200, await channel(id));
      return true;
    }
    if (route.startsWith("/podcast/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/podcast/".length));
      sendJson(res, 200, await podcast(id));
      return true;
    }
    if (route.startsWith("/episode/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/episode/".length));
      sendJson(res, 200, await episode(id));
      return true;
    }
    if (route === "/episodes-playlist" && method === "GET") {
      const id = url.searchParams.get("playlistId") || "SE";
      sendJson(res, 200, await episodesPlaylist(id));
      return true;
    }
    if (route.startsWith("/next/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/next/".length));
      const pl = url.searchParams.get("playlistId") || void 0;
      sendJson(res, 200, await upNext(id, pl));
      return true;
    }
    if (route.startsWith("/radio/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/radio/".length));
      sendJson(res, 200, await radio(id));
      return true;
    }
    if (route === "/queue-more" && method === "GET") {
      const token = url.searchParams.get("token") || "";
      sendJson(res, 200, token ? await queueMore(token) : { tracks: [], continuation: null });
      return true;
    }
    if (route.startsWith("/similar/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/similar/".length));
      sendJson(res, 200, { tracks: await similar(id) });
      return true;
    }
    if (route.startsWith("/rating/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/rating/".length));
      sendJson(res, 200, { status: await rating(id) });
      return true;
    }
    if (route.startsWith("/related/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/related/".length));
      sendJson(res, 200, await related(id));
      return true;
    }
    if (route.startsWith("/lyrics/") && method === "GET") {
      const id = decodeURIComponent(route.slice("/lyrics/".length));
      sendJson(res, 200, await lyrics(id));
      return true;
    }
    if (route === "/auth/status") {
      sendJson(res, 200, {
        authenticated: isAuthenticated(),
        login: getLoginState()
      });
      return true;
    }
    if (route === "/auth/login" && method === "POST") {
      const state = startLogin();
      sendJson(res, 200, { ok: true, login: state });
      return true;
    }
    if (route === "/auth/logout" && method === "POST") {
      logout();
      sendJson(res, 200, { ok: true });
      return true;
    }
    if (route === "/account" && method === "GET") {
      if (!isAuthenticated()) {
        sendJson(res, 401, { detail: "not authenticated" });
        return true;
      }
      sendJson(res, 200, await account());
      return true;
    }
    if (route.startsWith("/library/") || route === "/history") {
      if (!isAuthenticated()) {
        sendJson(res, 401, { detail: "not authenticated" });
        return true;
      }
      if (route === "/library/playlists") {
        sendJson(res, 200, { playlists: await libraryPlaylists() });
        return true;
      }
      if (route === "/library/liked") {
        sendJson(res, 200, { results: await likedSongs() });
        return true;
      }
      if (route === "/library/songs") {
        sendJson(res, 200, { results: await librarySongs() });
        return true;
      }
      if (route === "/library/albums") {
        sendJson(res, 200, { results: await libraryAlbums() });
        return true;
      }
      if (route === "/library/artists") {
        sendJson(res, 200, { results: await libraryArtists() });
        return true;
      }
      if (route === "/library/subscriptions") {
        sendJson(res, 200, { results: await librarySubscriptions() });
        return true;
      }
      if (route === "/library/podcasts") {
        sendJson(res, 200, { results: await libraryPodcasts() });
        return true;
      }
      if (route === "/library/uploads/songs") {
        sendJson(res, 200, { results: await libraryUploadSongs() });
        return true;
      }
      if (route === "/library/uploads/albums") {
        sendJson(res, 200, { results: await libraryUploadAlbums() });
        return true;
      }
      if (route === "/library/uploads/artists") {
        sendJson(res, 200, { results: await libraryUploadArtists() });
        return true;
      }
      if (route === "/history") {
        sendJson(res, 200, { sections: await history() });
        return true;
      }
      sendJson(res, 404, { detail: "not found" });
      return true;
    }
    const MUTATIONS = /* @__PURE__ */ new Set([
      "/rate",
      "/rate-playlist",
      "/feedback",
      "/subscribe",
      "/history/add",
      "/history/remove",
      "/taste-profile",
      "/upload",
      "/upload/delete",
      "/suggest/remove",
      "/playlist/create",
      "/playlist/delete",
      "/playlist/add",
      "/playlist/remove",
      "/playlist/move",
      "/playlist/rename"
    ]);
    if (MUTATIONS.has(route) && method === "POST") {
      if (!isAuthenticated()) {
        sendJson(res, 401, { detail: "not authenticated" });
        return true;
      }
      const b = await readBody(req);
      switch (route) {
        case "/rate":
          await rate(b.videoId, b.rating);
          break;
        case "/rate-playlist":
          await ratePlaylist(b.playlistId, b.rating);
          break;
        case "/feedback":
          await feedback(b.tokens ?? []);
          break;
        case "/history/add":
          await addHistoryItem2(b.videoId);
          break;
        case "/history/remove":
          await removeHistoryItems(b.tokens ?? []);
          break;
        case "/taste-profile":
          await setTasteProfile(b.selections ?? []);
          break;
        case "/upload": {
          const ok = await uploadSong2(b.filePath);
          sendJson(res, 200, { ok });
          return true;
        }
        case "/upload/delete":
          await deleteUploadEntity(b.entityId);
          break;
        case "/suggest/remove":
          await removeSearchSuggestions(b.tokens ?? []);
          break;
        case "/subscribe":
          await subscribe(b.channelId, !!b.subscribe);
          break;
        case "/playlist/create": {
          const playlistId = await createPlaylist(b.title, b.description, b.privacy);
          sendJson(res, 200, { ok: true, playlistId });
          return true;
        }
        case "/playlist/delete":
          await deletePlaylist(b.playlistId);
          break;
        case "/playlist/add":
          await addToPlaylist(b.playlistId, b.videoIds ?? []);
          break;
        case "/playlist/remove":
          await removeFromPlaylist(b.playlistId, b.items ?? []);
          break;
        case "/playlist/move":
          await movePlaylistItem(b.playlistId, b.setVideoId, b.successorSetVideoId);
          break;
        case "/playlist/rename":
          await renamePlaylist(b.playlistId, b.name);
          break;
      }
      sendJson(res, 200, { ok: true });
      return true;
    }
    sendJson(res, 404, { detail: "not found" });
    return true;
  } catch (e) {
    if (e instanceof NotAuthedError) {
      sendJson(res, 401, { detail: "not authenticated" });
    } else {
      sendJson(res, 500, { detail: String(e) });
    }
    return true;
  }
}

// server/serve.ts
var CONTENT_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8"
};
function inSea() {
  try {
    return sea.isSea();
  } catch {
    return false;
  }
}
function loadAsset(distDir, key) {
  if (inSea()) {
    try {
      return Buffer.from(sea.getAsset(key));
    } catch {
      return null;
    }
  }
  const fp = path2.join(distDir, key);
  if (fp.startsWith(distDir) && existsSync2(fp)) {
    try {
      return readFileSync2(fp);
    } catch {
      return null;
    }
  }
  return null;
}
function keyFor(pathname) {
  let p = decodeURIComponent(pathname);
  if (p.endsWith("/")) p += "index.html";
  return p.replace(/^\/+/, "");
}
function serveStatic(distDir, req, res) {
  const url = new URL(req.url || "/", "http://localhost");
  const key = keyFor(url.pathname);
  let body = loadAsset(distDir, key);
  let served = key;
  if (!body && !path2.extname(key)) {
    body = loadAsset(distDir, "index.html");
    served = "index.html";
  }
  if (!body) {
    res.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
    res.end("Not found");
    return;
  }
  const type = CONTENT_TYPES[path2.extname(served)] || "application/octet-stream";
  res.writeHead(200, {
    "Content-Type": type,
    "Cache-Control": served === "index.html" ? "no-cache" : "public, max-age=31536000, immutable"
  });
  res.end(body);
}
function startServer(opts = {}) {
  const host = opts.host || process.env.HOST || "127.0.0.1";
  const port = opts.port ?? (Number(process.env.PORT) || 0);
  const distDir = opts.distDir || process.env.YTM_DIST || path2.join(process.cwd(), "dist");
  const server = createServer((req, res) => {
    handle(req, res).then((handled) => {
      if (!handled) serveStatic(distDir, req, res);
    }).catch((e) => {
      if (!res.headersSent) {
        res.writeHead(500, { "Content-Type": "application/json" });
      }
      res.end(JSON.stringify({ detail: String(e) }));
    });
  });
  return new Promise((resolve, reject) => {
    server.once("error", reject);
    server.listen(port, host, () => {
      const addr = server.address();
      const actualPort = typeof addr === "object" && addr ? addr.port : port;
      resolve({
        url: `http://${host}:${actualPort}`,
        port: actualPort,
        host,
        server,
        close: () => new Promise((r) => server.close(() => r()))
      });
    });
  });
}

// server/standalone.ts
import { spawn as spawn2 } from "node:child_process";
var PORT = Number(process.env.PORT) || 5173;
var HOST = process.env.HOST || "127.0.0.1";
function openBrowser(url) {
  if (process.env.YTM_NO_OPEN) return;
  try {
    const [cmd, args] = process.platform === "win32" ? ["cmd", ["/c", "start", "", url]] : process.platform === "darwin" ? ["open", [url]] : ["xdg-open", [url]];
    const child = spawn2(cmd, args, { detached: true, stdio: "ignore" });
    child.on("error", () => {
    });
    child.unref();
  } catch {
  }
}
startServer({ port: PORT, host: HOST }).then(({ url }) => {
  console.log(`ytmusicnative is running at ${url}`);
  console.log("Press Ctrl+C to stop.");
  openBrowser(url);
});
