const targets=await (await fetch("http://127.0.0.1:9222/json")).json();
const page=targets.find(t=>t.type==="page"&&t.url.includes("music.youtube.com"));
const ws=new WebSocket(page.webSocketDebuggerUrl);
let id=0;const pend=new Map();
const cmd=(m,p)=>new Promise(r=>{const i=++id;pend.set(i,r);ws.send(JSON.stringify({id:i,method:m,params:p}));});
ws.addEventListener("message",e=>{const m=JSON.parse(e.data);if(m.id&&pend.has(m.id)){pend.get(m.id)(m);pend.delete(m.id);}});
await new Promise(r=>ws.addEventListener("open",r));
const expr=`(()=>{const mp=document.getElementById('movie_player');const r={};
  const tryc=(n,f)=>{try{r[n]=f()}catch(e){r[n]='ERR '+e.message}};
  tryc('userSetting',()=>mp.getUserAudioQualitySetting());
  tryc('settingState',()=>mp.getAudioQualitySettingState());
  tryc('paygated',()=>mp.getPaygatedAudioQualityData());
  tryc('hasHqa',()=>mp.hasHqaAudioTrack());
  tryc('trackState',()=>mp.getAudioTrackState());
  return JSON.stringify(r);
})()`;
const res=await cmd("Runtime.evaluate",{expression:expr,returnByValue:true});
console.log(JSON.stringify(JSON.parse(res.result.result.value),null,1));
ws.close();
